version: '3'

services:
  prometheus:
      image: prom/prometheus
      ports:
        - ${PROMETHEUS_PORT}:9090
      volumes: 
        - ./prometheus.yml:/etc/prometheus/prometheus.yml
      container_name: prometheus