version: '3'

services:
    postgres:
        image: postgres:11.1
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
        restart: always
        ports:
            - ${POSTGRES_PORT}:5432
        volumes:
            - ${POSTGRES_DATA}:/var/lib/postgresql/data
        container_name: postgres