
version: '3'
services:
  elasticsearch:
    image: bitnami/elasticsearch:latest
    volumes:
      - /home/ubuntu/data/elasticsearch:/bitnami
    restart: always
    container_name: elasticsearch
  kibana:
    image: bitnami/kibana:latest
    ports:
      - ${KIBANA_PORT}:5601
    volumes:
      - /home/ubuntu/data/kibana:/bitnami
    restart: always
    container_name: kibana
    depends_on:
      - elasticsearch
volumes:
  elasticsearch_data:
    driver: local
  kibana_data:
    driver: local
